### ISSUE TITLE
Disc Count is not resetting, When a new game is started

### ISSUE THREAD

**Issue by mythikosium** [TERNION-1121/Othello-Reversi-Game#1]
Please reset the disc Count back to 2 for both black and white. When 'R' is pressed.

Like in the below attached image. White won a game.
![image](https://github.com/TERNION-1121/Othello-Reversi-Game/assets/99966559/3f731f27-b949-4dfe-93d9-851f0c1d2936)

When the new game is started (by pressing 'R'). Then the disc Count instead of being reset to 2 for both; remains the same as the end of last game. As you can see in the image below.
![image](https://github.com/TERNION-1121/Othello-Reversi-Game/assets/99966559/396f984d-70e0-47ae-ad67-e92e66c67a58)

**Comment by TERNION-1121** [comment]
Thanks for reporting the issue, fixed it in the last [commit ](https://github.com/TERNION-1121/Othello-Reversi-Game/commit/838776cb6f0e0033eca84e682dab717ceb905ef5)
