### ISSUE TITLE
Error in minimax algorithm

### ISSUE THREAD

**Issue by HersheyZinc** [TERNION-1121/Othello-Reversi-Game#8]
Currently, the minmax algorithm only sets the value of the new disc via 
`position.board[row, col] = Board.BLACK`

This does not flip any discs and causes the final evaluation to be flawed.

Suggest to create a copy of the board and call `board.set_discs()`  instead

**Comment by TERNION-1121** [comment]
Greetings Zhe!
I'm really grateful for you stepping forward to pay your attention to the project. Means a lot :)

For the issue,
Firstly I realised I was a dumbster for not noticing this fact,
Secondly, I have created a [new branch](https://github.com/TERNION-1121/Othello-Reversi-Game/tree/minimax-error-fix) for fixing the same issue
I'd appreciate you checking the updated code for [minimax.py](https://github.com/TERNION-1121/Othello-Reversi-Game/blob/c1a0fcc52ef143a4329a7edd491de24061e465b2/src/utils/minimax.py#L56-L60)

I believe this code snippet should work to fix the problem (added this at two places in the `minimax` function, and once in the `find_best_move` function.

```py
position_deepcopy = deepcopy(position) # create a deep copy of the board position
position_deepcopy.board[row, col] = Board.WHITE
position_deepcopy.set_discs(row, col, Board.WHITE)

currentEval = minimax(position_deepcopy, 5, float('-inf'), float('inf'), True)
```

Let me know how does this seem like..
Thanks!!

**Comment by HersheyZinc** [comment]
Hi Vikrant,

The updated minimax algorithm works as intended now, though I believe the line `position_deepcopy.board[row, col] = Board.WHITE` is redundant as `set_disc()` already does that action.

**Comment by TERNION-1121** [comment]
Greetings Zhe,
Thanks for letting me know about that!
My eyes just didn't catch that line of code ;p
Fixed it with the latest commit 👍 

I shall mark this issue as closed as I merge the [`minimax-error-fix`](https://github.com/TERNION-1121/Othello-Reversi-Game/tree/minimax-error-fix) branch to main.
Thanks again!
