### ISSUE TITLE
check_game_over() faulty logic

### ISSUE THREAD

**Issue by HersheyZinc** [TERNION-1121/Othello-Reversi-Game#9]
In board.py Board.check_game_over() function, there seems to be faulty logic with the return statement.

```
if not possibleBlackMoves or not possibleWhiteMoves:
    return False
return True
```
Case: return False when either black or white has no moves.
Expectation: return True when both black and white have no moves.
Suggested fix:
```
if possibleBlackMoves or possibleWhiteMoves:
    return False
return True
```

Apologies if my formatting is messy as I am still unfamiliar with Github's workflow and standards.

**Comment by TERNION-1121** [comment]
I just can't thank you enough Zhe!
I was really light with the development of the minimax AI feature.

Thanks a lot for highlighting the issues,
I tried matching this fixed minimax with my friend's static weight evaluation, to which it had already lost many matches (I was puzzled why)
But this time it didn't.
Thanks again!!!

I shall close this issue by merging the [new branch](https://github.com/TERNION-1121/Othello-Reversi-Game/tree/fix-game-over-logic) created to fix this issue.
Lemme know if anything else lacks.
Always appreciating your efforts..

(and your issues are well written, p.s. practice makes one perfect!)
